# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e9f86e9bb9965751ef234367e12adbde3651da2bf1b67b3dd65f905d0594dd56386d230db64682f56cec217864c6af91b71cb4e90c98d651b489047d630854

test:
  secret_key_base: fd0196790d84b3808c2e7eca46f4429128b708ea45798f17607179cf5dcfbfb1a951d5a94d7c328f6f8aee08e5e35dd436612d2b90bab5cd97f05f0a71889f48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
